{{ if .Values.sync.config.secret.sealedValues }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.sync.config.secret.name }}
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "adguard-sync"
    {{- include "common.labels" . | nindent 4 }}
spec:
  encryptedData:
    ORIGIN_PASSWORD: {{ .Values.sync.config.secret.sealedValues.password }}
    {{ range $i, $v := untilStep 1 ((add1 .Values.secondary.replicas) | int ) 1 }}
    REPLICA{{ $v }}_PASSWORD: {{ $.Values.sync.config.secret.sealedValues.password }}
    {{ end }}
  template:
    metadata:
      name: {{ .Values.sync.config.secret.name }}
{{ end }}
