replicas: 1

resources: {}
#  requests:
#    memory: 512Mi
#    cpu: 100m
#  limits:
#    memory: 2048Mi

deploymentStrategy:
  type: Recreate

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  runAsNonRoot: true

securityContext:
  capabilities:
    drop: [ "ALL" ]
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  privileged: false

image:
  registry: docker.io
  repository: infrolabs/infro-core
  tag: latest@sha256:c2293d7611a64aaa8a101de2d2b35eba6e170f98
  pullPolicy: IfNotPresent

config:
  existingSecretName:
  owner:
  config:
