{{- if .Values.database.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ template "common.fullname" . }}-data
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "immich"
    {{- include "common.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      "cnpg.io/cluster": {{ .Values.database.clusterName }}
  podMetricsEndpoints:
    - port: metrics
  {{- end }}
