{{- if .Values.postgresql.external -}}
apiVersion: v1
kind: Secret
metadata:
  name: dependencytrack-postgresql
  labels:
{{ include "dependency-track.labels" . | indent 4 }}
type: Opaque
data: 
  postgresql-password: {{ .Values.postgresql.postgresqlPassword  | b64enc | quote }}
{{- end -}}
