apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "generic-device-plugin"
    {{- include "labels" . | nindent 4 }}
data:
  config.yaml: |
    devices: {{ .Values.devices | toYaml | nindent 4 }}
