apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "common.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "common.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "core"
    {{- include "labels" . | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  replicas: {{ .Values.replicas }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "common.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: "core"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "common.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: "core"
        {{- include "labels" . | nindent 8 }}
    spec:
      nodeSelector: {{ .Values.nodeSelector | toYaml | nindent 8 }}
      securityContext: {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: core
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - poll
            - --owner
            - $(owner)
            - --config
            - $(config)
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          resources: {{ toYaml .Values.resources | nindent 12 }}
          securityContext: {{ toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- $secretName := default ( include "common.fullname" . ) .Values.config.existingSecretName }}
            - name: config
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: config
            - name: owner
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: owner
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      volumes:
        - name: tmp
          emptyDir: {}
