{{- if not .Values.config.existingSecretName }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "infro.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "infro.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: "core"
    {{- include "labels" . | nindent 4 }}
stringData:
    owner: {{ .Values.config.owner | quote }}
    config: {{ .Values.config.config | quote }}
{{- end }}
